# Generated by Django 5.2.10 on 2026-01-18 10:35

from django.db import migrations

import citext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=citext.fields.CIEmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
