# Generated by Django 5.2.10 on 2026-01-18 20:30

import citext.fields
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


def set_role_for_superuser(apps, schema_editor):
    """Set role to ADMIN for existing superusers.

    We need to set role for existing superusers to ADMIN,
    because by default role is CLIENT.

    """
    User = apps.get_model("users", "User")
    superusers = User.objects.filter(is_superuser=True)
    for user in superusers:
        user.role = "admin"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', citext.fields.CIEmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=50, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.client', verbose_name='Client'),
        ),
        migrations.RunPython(set_role_for_superuser),
    ]
